global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["host.docker.internal:8000"]  # Update for your FastAPI host and port

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
